/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * configuracaoBackup.java
 *
 * Created on 23/06/2010, 13:39:06
 */
package backupmysqlgmail;


import java.util.List;
import javax.swing.JOptionPane;
import util.DAOGenerico;

/**
 *
 * @author Frank
 */
public class configuracaoBackup extends javax.swing.JDialog {

    private entidadeBackup backup;

    /** Creates new form configuracaoBackup */
    public configuracaoBackup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        backup = new entidadeBackup();
        setLocationRelativeTo(null);
        setConfiguracao();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void setConfiguracao() {
        List<entidadeBackup> bac = new DAOGenerico<entidadeBackup>(entidadeBackup.class).list();
        if (bac.size() > 0) {
            entidadeBackup bc = bac.get(0);
            tfNomeBase.setText(bc.getNomeBaseDados());
         
            tfDiretorioSalvar.setText(bc.getDiretorioSalvarSql());
          
            tfNomeUsuario.setText(bc.getUsuarioBase());
            tfSenhaBase.setText(bc.getSenhaBase());
            tfEnderecoServidor.setText(bc.getEnderecoServidor());
            backup = bc;
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeBase = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNomeUsuario = new javax.swing.JTextField();
        tfSenhaBase = new javax.swing.JPasswordField();
        tfDiretorioSalvar = new javax.swing.JTextField();
        tfEnderecoServidor = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ExemploNomeBase = new javax.swing.JButton();
        ExemploNomeUsuario = new javax.swing.JButton();
        ExemploSenhaBase = new javax.swing.JButton();
        ExemploDiretorioSalvar = new javax.swing.JButton();
        ExemploEndNomeServidor = new javax.swing.JButton();
        BtSalvar = new javax.swing.JButton();
        BtFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("..:: Configurações de Backup ::..");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setText("Nome Base:");

        jLabel6.setText("Nome Usuário:");

        jLabel7.setText("Nome Servidor ou Endereço IP:");

        jLabel4.setText("Local do Diretório (Salvar/Dump):");

        jLabel2.setText("Senha Base:");

        ExemploNomeBase.setText("Ajuda(?)");
        ExemploNomeBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemploNomeBaseActionPerformed(evt);
            }
        });

        ExemploNomeUsuario.setText("Ajuda(?)");
        ExemploNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemploNomeUsuarioActionPerformed(evt);
            }
        });

        ExemploSenhaBase.setText("Ajuda(?)");
        ExemploSenhaBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemploSenhaBaseActionPerformed(evt);
            }
        });

        ExemploDiretorioSalvar.setText("Ajuda(?)");
        ExemploDiretorioSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemploDiretorioSalvarActionPerformed(evt);
            }
        });

        ExemploEndNomeServidor.setText("Ajuda(?)");
        ExemploEndNomeServidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExemploEndNomeServidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfSenhaBase, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(tfNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                    .addComponent(tfNomeBase, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ExemploNomeBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ExemploNomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ExemploSenhaBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDiretorioSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ExemploDiretorioSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEnderecoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ExemploEndNomeServidor)
                        .addContainerGap(18, Short.MAX_VALUE))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfDiretorioSalvar, tfEnderecoServidor, tfNomeBase, tfNomeUsuario, tfSenhaBase});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExemploDiretorioSalvar, ExemploNomeBase, ExemploNomeUsuario, ExemploSenhaBase});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ExemploNomeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfNomeBase)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ExemploNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSenhaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ExemploSenhaBase, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfDiretorioSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(ExemploDiretorioSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfEnderecoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExemploEndNomeServidor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfDiretorioSalvar, tfEnderecoServidor, tfNomeBase, tfNomeUsuario, tfSenhaBase});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel4, jLabel6, jLabel7});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ExemploNomeBase, ExemploNomeUsuario});

        BtSalvar.setText("Salvar");
        BtSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSalvarActionPerformed(evt);
            }
        });

        BtFechar.setText("Fechar");
        BtFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtSalvar)
                        .addGap(327, 327, 327)
                        .addComponent(BtFechar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtFechar, BtSalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtSalvar)
                    .addComponent(BtFechar))
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtFechar, BtSalvar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSalvarActionPerformed
        if (VerificarCampos()) {
            if (backup == null) {
                entidadeBackup b = new entidadeBackup();
                b.setNomeBaseDados(tfNomeBase.getText());
                b.setEnderecoServidor(tfEnderecoServidor.getText());
                b.setSenhaBase(tfSenhaBase.getText());
            
                b.setDiretorioSalvarSql(tfDiretorioSalvar.getText());
        
                b.setUsuarioBase(tfNomeUsuario.getText());
                new DAOGenerico<entidadeBackup>(entidadeBackup.class).insert(b);
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            } else {
                backup.setNomeBaseDados(tfNomeBase.getText());
                backup.setEnderecoServidor(tfEnderecoServidor.getText());
                backup.setSenhaBase(tfSenhaBase.getText());
                backup.setUsuarioBase(tfNomeUsuario.getText());
             
                backup.setDiretorioSalvarSql(tfDiretorioSalvar.getText());
              
                new DAOGenerico<entidadeBackup>(entidadeBackup.class).update(backup);
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso");
            }
        }
    }//GEN-LAST:event_BtSalvarActionPerformed

    private void BtFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtFecharActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BtFecharActionPerformed

    private void ExemploNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemploNomeUsuarioActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Nome de usuário do banco de dados  ");
    }//GEN-LAST:event_ExemploNomeUsuarioActionPerformed

    private void ExemploNomeBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemploNomeBaseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Nome do banco de dados da aplicação  ");
    }//GEN-LAST:event_ExemploNomeBaseActionPerformed

    private void ExemploSenhaBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemploSenhaBaseActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Senha do usuário do banco de dados  ");
    }//GEN-LAST:event_ExemploSenhaBaseActionPerformed

    private void ExemploDiretorioSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemploDiretorioSalvarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Diretório que será armazenado o Backup, MysqlDump e Mysql, Exemplo: \n                             C:/backup  ");
    }//GEN-LAST:event_ExemploDiretorioSalvarActionPerformed

    private void ExemploEndNomeServidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExemploEndNomeServidorActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Nome da máquina servidor ou endereço de IP  ");
    }//GEN-LAST:event_ExemploEndNomeServidorActionPerformed

    private boolean VerificarCampos() {
        if (tfNomeBase.getText().trim().equals("")&&(tfNomeUsuario.getText().trim().equals("")&&(tfSenhaBase.getText().trim().equals("")&&
           ((tfDiretorioSalvar.getText().trim().equals("")&&(
           (tfEnderecoServidor.getText().trim().equals("")))))))){
            JOptionPane.showMessageDialog(this," Por Favor, Preecha todos os campos " );
            tfNomeBase.requestFocus();
            return false;
        }

        if (tfNomeBase.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, " ' Nome Base ' Inválido ! ");
            tfNomeBase.requestFocus();
            return false;
        }
        if (tfNomeUsuario.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, " ( Nome do Usuáro ) Inválido  ");
            tfNomeUsuario.requestFocus();
            return false;
        }
        /*if (tfSenhaBase.getText().trim().equals("")) {
        JOptionPane.showMessageDialog(this, " ( Senha Base ) Inválido  ");
        tfSenhaBase.requestFocus();
        return false;
        }*/
       
        if (tfDiretorioSalvar.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, " ( Diretório a ser Salvo ) Inválido  ");
            tfDiretorioSalvar.requestFocus();
            return false;
        }
       
        if (tfEnderecoServidor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, " ( Endereço do Servidor ) Inválido  ");
            tfEnderecoServidor.requestFocus();
            return false;
        
           
        } else {
            return true;
        }
    }


   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                configuracaoBackup dialog = new configuracaoBackup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtFechar;
    private javax.swing.JButton BtSalvar;
    private javax.swing.JButton ExemploDiretorioSalvar;
    private javax.swing.JButton ExemploEndNomeServidor;
    private javax.swing.JButton ExemploNomeBase;
    private javax.swing.JButton ExemploNomeUsuario;
    private javax.swing.JButton ExemploSenhaBase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfDiretorioSalvar;
    private javax.swing.JTextField tfEnderecoServidor;
    private javax.swing.JTextField tfNomeBase;
    private javax.swing.JTextField tfNomeUsuario;
    private javax.swing.JPasswordField tfSenhaBase;
    // End of variables declaration//GEN-END:variables
}
